This is the beginning of the project.

In [1]:
'Setting up Imports'
import pandas as pd
import re

In [2]:
CFI = pd.read_csv("./data/Public_CFI_Network_Directory.2025-3-30.csv")
HIP = pd.read_csv("./data/High Impact Professionals - Public Talent Directory-2.csv")

HIP.head()

,Full Name,Open to,Cause Areas,Roles: Interested,Roles: 1+ years of experience,Years of Work Experience,Professional Summary / Experience,LinkedIn/CV Link,How interested are you in moving into a (new) high-impact job?,How interested are you in founding/co-founding a new high-impact project?,...,Languages,Work Location Preference,Willing to Relocate,Willing to Relocate - Context,Current Employment Status,Money Managed,Max Staff Managed,Other Interests,Profile Last Updated,Outdated Candidate
0,Jordon Harris,"Part-time,Freelance","Animal welfare,Climate change,Environment and ...","Administrative,Business Development,Communicat...","Business Development,Communications,Event Orga...",5.0,With a proven track record of driving results ...,https://www.linkedin.com/in/jordonftempletonha...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,English,Fully remote,No,NaN,Freelancing,US$2000000,10.0,"Running a EA workplace or professional group,A...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
1,Malavika Malaviya,"Full-time,Part-time,Freelance","Animal welfare,Environment and sustainability","Animal Health / Welfare,Arts and Creative,Busi...","Animal Health / Welfare,Arts & Creative,Busine...",13.0,Vegan lifestyle advocate and founder of @malag...,https://www.linkedin.com/in/malavika-malaviya-...,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi,Bengali","Fully remote,Partially remote / Hybrid,In-person",Yes,NaN,Working full time,US$1000000,10.0,"Advisor - Advising an effective organization,B...",2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
2,Chandrakiran HJ,"Full-time,Internship","AI strategy and policy,AI technical research",Product Management,Product Management,1.0,"As a driven student at IIIT B, I thrive on ide...",http://linkedin.com/in/chandrakiran-hj-835b65196,5 - I’m actively trying to do this,5 - I’m actively trying to do this,...,"English,Hindi","Partially remote / Hybrid,Fully remote,In-person",Yes,NaN,Studying,NaN,NaN,NaN,2025-03-29,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
3,Natalie Darby,"Part-time,Full-time,Volunteering","AI strategy and policy,Cybersecurity,Education...","Administrative,Accounting,Business Development...","Accounting,Administrative,Communications,Educa...",30.0,"Broad range of experience in operations, finan...",https://www.linkedin.com/in/natalie-darby/,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,English,Partially remote / Hybrid,Maybe,I'd work for a time overseas but my home is Au...,"Volunteering,Working part time",US$1200000,15.0,"Advisor - Advising an effective organization,B...",2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...
4,Kaitlin Roberts,"Full-time,Part-time","Animal welfare,Climate change,Civilization Res...","Animal Health / Welfare,Arts and Creative,Camp...","Arts & Creative,Community building,Business De...",10.0,Experienced audio storyteller and communicatio...,https://www.linkedin.com/me?trk=p_mwlite_feed-...,5 - I’m actively trying to do this,3 - Not actively looking but would consider a ...,...,"German,English","Fully remote,Partially remote / Hybrid,In-person",Maybe,I am not willing to move to the US,"Freelancing,Volunteering,Studying,Unemployed /...",NaN,6.0,NaN,2025-03-28,https://airtable.com/shrSvHwSxxAOAPDxO?prefill...

I don't currently know any details about these datasets. I don't want to prematurely drop any important records, especially when I don't know anything about them. The goal here is that eventually, we will merge the datasets together. First, we will clean each dataset separately, before we merge, hopefully using concatenation. This will ensure better data integrity, and concatenation will keep all unique entries rather than only the overlapping observations.

In [3]:
# data profiling: check column types, summarize missing values, look at unique values of categorical fields to identify inconsistencies, generate descriptive statistics

def data_profiling(df):
    print("**Basic Data Overview**")
    print(df.info())
    print("\n")
    
    print("**Missing Values Summary**")
    missings = df.isnull().sum()
    print(missings[missings > 0])
    print("\n")
    
    print("**Unique Values in Categorical Columns**")
    categories = df.select_dtypes(include=['object']).columns
    for col in categories:
        unique_values = df[col].unique()
        print(f"{col}: {len(unique_values)} unique values")
        print(f"Sample values: {unique_values[:10]}")
    print("\n")
    
    print("**Descriptive Statistics for Numeric Columns**")
    print(df.describe())

In [4]:
data_profiling(CFI)

**Basic Data Overview**
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356 entries, 0 to 355
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Full Name               356 non-null    object
 1   City                    354 non-null    object
 2   Country                 355 non-null    object
 3   Current Title           327 non-null    object
 4   Current Employer        222 non-null    object
 5   Large Firm Affiliation  141 non-null    object
 6   LinkedIn                353 non-null    object
 7   Career Path Interests   312 non-null    object
 8   Cause Area Interests    264 non-null    object
 9   Openness to a New Role  243 non-null    object
dtypes: object(10)
memory usage: 27.9+ KB
None


**Missing Values Summary**
City                        2
Country                     1
Current Title              29
Current Employer          134
Large Firm Affiliation    215
LinkedIn                    3
Career Path Interests      44
Cause Area Interests       92
Openness to a New Role    113
dtype: int64


**Unique Values in Categorical Columns**
Full Name: 355 unique values
Sample values: ['Abdullah  Al Qayyim' 'Aditi Sharma' 'Andrew  Dornon' 'Anurag Dey'
 'Barth Cabouat' 'Carlo  Cristobal' 'Carolin  Oelschläger'
 'Celine  Delacharlerie' 'Clara  Ruiz Linaje' 'David Aguirre']
City: 182 unique values
Sample values: ['New Brunswick' 'Bangalore' 'Austin' 'Stockholm' 'Nairobi'
 'Washington DC' 'Hamburg' 'Singapore' 'Montreal' 'Sydney']
Country: 55 unique values
Sample values: ['Canada' 'India' 'United States of America' 'Sweden' 'Kenya' 'Germany'
 'Singapore' 'Australia' 'United Kingdom' 'Netherlands']
Current Title: 11 unique values
Sample values: ['Independent consultant' 'Consultant (2-4 years experience)' 'Other'
 'Junior consultant (0-2 years consulting experience)'
 'Managing Director and Partner' 'Project leader (4-6 years experience)'
 'Student' nan 'Founder' 'Partner']
Current Employer: 194 unique values
Sample values: ['Abdullahandbeyond, MCAF' 'VMware' 'TaskHuman' 'Analysys Mason'
 'One Acre Fund' nan 'Kumi health gmbH' 'Scalable Impact' 'EIDU'
 'Blue Horizon']
Large Firm Affiliation: 13 unique values
Sample values: [nan 'Boston Consulting Group' 'Deloitte' 'Accenture' 'Ernst & Young'
 'McKinsey' 'None (e.g. student)' 'Bain' 'KPMG' 'PricewaterhouseCoopers']
LinkedIn: 353 unique values
Sample values: ['https://www.linkedin.com/in/abdullahandbeyond/'
 'https://www.linkedin.com/in/aditishm/'
 'https://www.linkedin.com/in/andrewdornon/'
 'https://www.linkedin.com/in/anuragdey/'
 'https://www.linkedin.com/in/barthcabouat/'
 'https://www.linkedin.com/in/carlocristobal/' nan
 'https://www.linkedin.com/in/celinedelacharlerie/'
 'https://www.linkedin.com/in/clararuizlinaje/'
 'https://www.linkedin.com/in/mdaguirre/']
Career Path Interests: 298 unique values
Sample values: [nan 'Academic research,Healthcare/Medicine,Operations'
 'Technology,Operations,Communications/Marketing'
 'Technology,Product management' 'Product management,Technology'
 'Outreach & Community Building'
 'Technology,Data science/Data visualization,Operations'
 'Operations,Finance/Accounting' 'Academic research,Technology'
 'Politics,Policy/Government']
Cause Area Interests: 260 unique values
Sample values: [nan
 'Animal welfare,Environment and sustainability,Climate change,Poverty and health ( low-income and middle-income countries)'
 'Climate change,Environment and sustainability,Scientific/technological progress and economic growth'
 'Longtermism,Climate change,Environment and sustainability,Scientific/technological progress and economic growth,Space governance'
 'Scientific/technological progress and economic growth,Bio risk reduction,Risks posed by artificial intelligence (technical),Risks posed by artificial intelligence (policy)'
 'Improving institutional decision making'
 'Risks posed by artificial intelligence (technical),Risks posed by artificial intelligence (policy)'
 'Building effective altruism'
 'Risks posed by artificial intelligence (technical),Risks posed by artificial intelligence (policy),Mental health'
 'Global priorities research,Poverty and health (high-income areas),Building effective altruism,Risks posed by artificial intelligence (policy),Education and employment,Environment and sustainability']
Openness to a New Role: 2 unique values
Sample values: [nan True]


**Descriptive Statistics for Numeric Columns**
                 Full Name    City                   Country  \
count                  356     354                       355
unique                 355     181                        54
top     Haindavi  Kandarpa  London  United States of America
freq                     2      44                       109

                            Current Title    Current Employer  \
count                                 327                 222
unique                                 10                 193
top     Consultant (2-4 years experience)  McKinsey & Company
freq                                   64                   5

         Large Firm Affiliation                                  LinkedIn  \
count                       141                                       353
unique                       12                                       352
top     Boston Consulting Group  https://www.linkedin.com/in/nwheeler443/
freq                         32                                         2

       Career Path Interests  \
count                    312
unique                   297
top               Management
freq                       4

                                     Cause Area Interests  \
count                                                 264
unique                                                259
top     Climate change,Environment and sustainability,...
freq                                                    2

       Openness to a New Role
count                     243
unique                      1
top                      True
freq                      243

In [5]:
data_profiling(HIP)

**Basic Data Overview**
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2374 entries, 0 to 2373
Data columns (total 26 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   Full Name                                                                  2374 non-null   object
 1   Open to                                                                    2369 non-null   object
 2   Cause Areas                                                                2374 non-null   object
 3   Roles: Interested                                                          2373 non-null   object
 4   Roles: 1+ years of experience                                              2360 non-null   object
 5   Years of Work Experience                                                   2368 non-null   float64
 6   Professional Summary / Experience                                          2246 non-null   object
 7   LinkedIn/CV Link                                                           2370 non-null   object
 8   How interested are you in moving into a (new) high-impact job?             2374 non-null   object
 9   How interested are you in founding/co-founding a new high-impact project?  1919 non-null   object
 10  New Project - Needs                                                        1308 non-null   object
 11  Time spent engaging with Effective Altruism (EA)                           2370 non-null   object
 12  Available From                                                             2369 non-null   object
 13  Country                                                                    2372 non-null   object
 14  City                                                                       2255 non-null   object
 15  Timezone                                                                   2359 non-null   object
 16  Languages                                                                  2368 non-null   object
 17  Work Location Preference                                                   2372 non-null   object
 18  Willing to Relocate                                                        2371 non-null   object
 19  Willing to Relocate - Context                                              1578 non-null   object
 20  Current Employment Status                                                  2373 non-null   object
 21  Money Managed                                                              1569 non-null   object
 22  Max Staff Managed                                                          1930 non-null   float64
 23  Other Interests                                                            1983 non-null   object
 24  Profile Last Updated                                                       2374 non-null   object
 25  Outdated Candidate                                                         2374 non-null   object
dtypes: float64(2), object(24)
memory usage: 482.3+ KB
None


**Missing Values Summary**
Open to                                                                         5
Roles: Interested                                                               1
Roles: 1+ years of experience                                                  14
Years of Work Experience                                                        6
Professional Summary / Experience                                             128
LinkedIn/CV Link                                                                4
How interested are you in founding/co-founding a new high-impact project?     455
New Project - Needs                                                          1066
Time spent engaging with Effective Altruism (EA)                                4
Available From                                                                  5
Country                                                                         2
City                                                                          119
Timezone                                                                       15
Languages                                                                       6
Work Location Preference                                                        2
Willing to Relocate                                                             3
Willing to Relocate - Context                                                 796
Current Employment Status                                                       1
Money Managed                                                                 805
Max Staff Managed                                                             444
Other Interests                                                               391
dtype: int64


**Unique Values in Categorical Columns**
Full Name: 2359 unique values
Sample values: ['Jordon Harris' 'Malavika Malaviya' 'Chandrakiran HJ' 'Natalie Darby'
 'Kaitlin Roberts' 'Manasa  Ram Raj' 'Jason  Pinelo' 'Marita Calderón'
 "Brenton O'Hara" 'Jamila Musa']
Open to: 130 unique values
Sample values: ['Part-time,Freelance' 'Full-time,Part-time,Freelance'
 'Full-time,Internship' 'Part-time,Full-time,Volunteering'
 'Full-time,Part-time' 'Full-time,Freelance' 'Full-time'
 'Internship,Volunteering' 'Full-time,Part-time,Freelance,Volunteering'
 'Full-time,Part-time,Internship,Volunteering']
Cause Areas: 2047 unique values
Sample values: ['Animal welfare,Climate change,Environment and sustainability,Global health and development,Wild animal welfare,Mental health,Human rights'
 'Animal welfare,Environment and sustainability'
 'AI strategy and policy,AI technical research'
 'AI strategy and policy,Cybersecurity,Education and employment,Economic inequality,Effective giving,Environment and sustainability,Technological / economic growth,Refugees and immigration,Peace / stability / great power relations,Mental health,Improving institutional decision making,Human rights,Global priorities research,Global health and development,EA meta,EA movement building/growth'
 'Animal welfare,Climate change,Civilization Resilience,Economic inequality,Environment and sustainability,Human rights,Wild animal welfare'
 'Equality (e.g. gender / racial / LGBTQ+ / etc),Epistemic institutions,Environment and sustainability,Education and employment,Economic inequality,Climate change,Civilization Resilience,Existential risk reduction,Global priorities research,Human rights,Peace / stability / great power relations'
 'AI strategy and policy,AI technical research,Authoritarianism and corruption,Civilization Resilience,Education and employment,Improving institutional decision making,Risks posed by artificial intelligence,Technological / economic growth'
 'Animal welfare,Climate change,EA movement building/growth,Wild animal welfare,Environment and sustainability'
 'AI technical research,EA meta,EA movement building/growth,Earning to give,Effective giving,Education and employment,Equality (e.g. gender / racial / LGBTQ+ / etc),Existential risk reduction,Risks posed by artificial intelligence,Technological / economic growth,Animal welfare,Wild animal welfare,Environment and sustainability,Economic inequality,Global priorities research,Improving institutional decision making,Mental health,Human rights,Global health and development,AI strategy and policy,Space governance,Refugees and immigration,Epistemic institutions,Climate change,Civilization Resilience,Biosecurity and pandemic preparedness'
 'Global health and development']
Roles: Interested: 2330 unique values
Sample values: ['Administrative,Business Development,Communications,Community building,Marketing,Personal Assistant / Executive Assistant,Social Media,Project Management,Human Resources & People Ops,Customer Success,Corporate Engagement'
 'Animal Health / Welfare,Arts and Creative,Business Development,Campaigns,Communications,Community building,Consulting,Corporate Engagement,Education,Entrepreneurship,Event Organizing,Fundraising,Grantmaking,Leadership and Management,Marketing,Outreach,Public Relations / PR,Research,Social Media,Strategy'
 'Product Management'
 'Administrative,Accounting,Business Development,Campaigns,Communications,Consulting,Corporate Engagement,Customer Success,Data science,Design,Education,Finance,Forecasting,Fundraising,Government,Grantmaking,Human Resources & People Ops,Leadership and Management,Operations,Project Management,Program Management,Quality Assurance,Research,R&D,Strategy'
 'Animal Health / Welfare,Arts and Creative,Campaigns,Communications,Education,Entrepreneurship,Strategy,Research,Project Management,Marketing'
 'Administrative,Campaigns,Communications,Community building,Consulting,Corporate Engagement,Data science,Education,Fundraising,Leadership and Management,Legal,Policy,Program Management,Research,Strategy'
 'Customer Success,Consulting,Human Resources & People Ops,Leadership and Management,Scientist,Software development / Tech,Science,Strategy'
 'Campaigns,Communications,Community building,Policy,Strategy,Research,Project Management,Education,Consulting'
 'Administrative,Consulting,Event Organizing,Entrepreneurship,Human Resources & People Ops,Leadership and Management,Operations,Program Management,Project Management,Grantmaking,Finance'
 'Medical & Health,Operations,Personal Assistant / Executive Assistant,Program Management,Research']
Roles: 1+ years of experience: 2117 unique values
Sample values: ['Business Development,Communications,Event Organizing,Marketing,Project Management,Sales,Strategy'
 'Animal Health / Welfare,Arts & Creative,Business Development,Communications,Community building,Campaigns,Corporate Engagement,Entrepreneurship,Marketing,Policy,Research,Social Media,Strategy'
 'Product Management'
 'Accounting,Administrative,Communications,Education,Finance,Human Resources & People Ops,Leadership and Management,Research,Quality Assurance,Program Management,Project Management,Operations,Medical & Health'
 'Arts & Creative,Community building,Business Development,Entrepreneurship,Product Management,Project Management'
 'Administrative,Campaigns,Communications,Community building,Corporate Engagement,Design,Event Organizing,Leadership and Management,Legal,Operations,Outreach,Policy,Program Management,Project Management,Research,Social Media,Strategy'
 'Engineering,IT,Software development / Tech'
 'Campaigns,Communications,Grantmaking,Research,Strategy,Social Media,Outreach,Event Organizing,Community building,Arts & Creative'
 'Consulting,Event Organizing,Human Resources & People Ops,Operations,Leadership and Management,Project Management,Program Management'
 'Medical & Health,Program Management,Research']
Professional Summary / Experience: 2247 unique values
Sample values: ['With a proven track record of driving results across marketing, sales, and operations, I bring precision, cross-functional collaboration, and a data-driven mindset to elevate your team’s efficiency and impact. My diverse experience, from scaling live event attendance to resolving high-stakes student emergencies as a college leader, equips me to adapt swiftly, solve complex challenges, and deliver measurable success in fast-paced environments.'
 'Vegan lifestyle advocate and founder of @malagoesgreen (16K followers), driving awareness through content, brand collaborations, and community engagement. Previously spent 10+ years in finance and policy at PwC, Michael Page, and Airtel. MBA from Cass Business School, University of London.'
 'As a driven student at IIIT B, I thrive on ideation, creation, and innovative problem-solving. Deeply rooted in the product management space, I’m now channeling my passion toward the transformative potential of AI agentic technologies—bridging technical innovation with real-world impact.'
 'Broad range of experience in operations, finance, learning and development, health and change management. I love working with people, systems and process to improve efficiency.'
 'Experienced audio storyteller and communications strategist with a background at The New York Times and Gimlet Media, where I led projects on environmental issues and human-animal relationships. Passionate about using storytelling to drive empathy and action for animal rights.'
 'Gender equity researcher and advocate with 7+ years leading community programs to eradicate violence against women and girls. Designed 5+ digital literacy initiatives to bridge the gender digital divide; spearheaded research-based advocacy on caste/gender-based violence; analyzed national/international gender case laws to shape policy frameworks. Partnered with NGOs, legal experts, and grassroots collectives to drive systemic change.'
 'Data and AI Engineer, currently training my management skills organizing and assigning activities to EA UPY members in order to accomplish EA UPY Goals in record time'
 'Dedicated communications for social change specialist focused on research and policies. Experience supporting campaigns, research and advocacy for human rights and climate justice (Amnesty International Americas).  Passionate about transdisciplinary collaboration. Intersectional activist for animals. '
 'Operations professional with 10+ years working for nonprofit organizations of all sizes in the US'
 'Pharmacist and public health professional with experience in health program management, research, and policy analysis. ']
LinkedIn/CV Link: 2353 unique values
Sample values: ['https://www.linkedin.com/in/jordonftempletonharris/'
 'https://www.linkedin.com/in/malavika-malaviya-b2600317/'
 'http://linkedin.com/in/chandrakiran-hj-835b65196'
 'https://www.linkedin.com/in/natalie-darby/'
 'https://www.linkedin.com/me?trk=p_mwlite_feed-secondary_nav'
 'https://www.linkedin.com/in/manasaramraj/'
 'https://www.linkedin.com/in/jason-pinelo-14a6a81a5/'
 'https://www.linkedin.com/in/maritacalderon/?locale=en_US '
 'https://www.linkedin.com/in/brentonrohara/'
 'www.linkedin.com/in/jamila-m-013284ab']
How interested are you in moving into a (new) high-impact job?: 5 unique values
Sample values: ['5 - I’m actively trying to do this'
 '1 - I’m not interested in changing roles right now'
 '3 - Not actively looking but would consider a role' '4' '2']
How interested are you in founding/co-founding a new high-impact project?: 6 unique values
Sample values: ['5 - I’m actively trying to do this'
 '3 - Not actively looking but would consider a role' '4'
 '1 - I’m not interested in changing roles right now' '2' nan]
New Project - Needs: 40 unique values
Sample values: [nan 'Collaborators' 'Collaborators,Funding,Project Idea'
 'Funding,Collaborators' 'Other' 'Collaborators,Project Idea,Funding'
 'Collaborators,Funding' 'Funding' 'Project Idea'
 'Collaborators,Funding,Project Idea,Other']
Time spent engaging with Effective Altruism (EA): 6 unique values
Sample values: ['5h - 20h' '20h -100h' '100h+' '<5h'
 'Never heard of "Effective Altruism"/"EA"' nan]
Available From: 477 unique values
Sample values: ['April 16, 2025' 'March 29, 2025' 'April 1, 2025' 'April 7, 2025'
 'June 1, 2025' 'March 27, 2025' 'May 1, 2025' 'March 29, 2027'
 'June 15, 2025' 'September 1, 2025']
Country: 176 unique values
Sample values: ['United States of America' 'India' 'Australia' 'Germany' 'Mexico'
 'Nigeria' 'Canada' 'United Kingdom' 'France' 'Czechia (Czech Republic)']
City: 1112 unique values
Sample values: ['Pittsburgh' 'New Delhi' 'Mysuru' 'Sydney' 'Berlin' 'Hubli' 'Merida'
 'Freiburg im Breisgau' 'Vancouver, WA' nan]
Timezone: 63 unique values
Sample values: ['UTC-05:00 Eastern Time (US and Canada)' 'UTC+05:00  Islamabad - Karachi'
 'UTC-11:00 Coordinated Universal Time-11' 'UTC+11:00 Sydney - Melbourne'
 'UTC+01:00 Amsterdam - Berlin - Bern - Rome - Stockholm - Vienna'
 'UTC+06:00 Dhaka' 'UTC-06:00 Central Time (US and Canada)'
 'UTC-08:00 Pacific Time (US and Canada)'
 'UTC±00:00 Dublin - Edinburgh - Lisbon - London'
 'UTC-12:00 International Date Line West']
Languages: 409 unique values
Sample values: ['English' 'English,Hindi,Bengali' 'English,Hindi' 'German,English'
 'English,Hindi,Tamil' 'Spanish,English,Italian' 'English,Spanish'
 'English,Chinese (Mandarin)' 'English,French' 'Spanish,English,French']
Work Location Preference: 15 unique values
Sample values: ['Fully remote' 'Fully remote,Partially remote / Hybrid,In-person'
 'Partially remote / Hybrid,Fully remote,In-person'
 'Partially remote / Hybrid'
 'In-person,Partially remote / Hybrid,Fully remote'
 'Fully remote,Partially remote / Hybrid'
 'Partially remote / Hybrid,In-person,Fully remote'
 'Partially remote / Hybrid,In-person'
 'Partially remote / Hybrid,Fully remote'
 'Fully remote,In-person,Partially remote / Hybrid']
Willing to Relocate: 10 unique values
Sample values: ['No' 'Yes' 'Maybe' 'Yes,Maybe' 'Maybe,No' 'No,Maybe' 'Maybe,No,Yes'
 'Maybe,Yes' 'Yes,No' nan]
Willing to Relocate - Context: 1488 unique values
Sample values: [nan "I'd work for a time overseas but my home is Australia."
 'I am not willing to move to the US'
 'I am willing to relocate to any place with good opportunity. '
 'Willing to move to Bay Area'
 "I'm currently studying a master's degree in Environmental governance, therefore I can only move from Freiburg during weekends or relocate during semester breaks (even 2 months)"
 'I am due to move to the Netherlands in July 2025. '
 'Dependent on role, I would consider any location.'
 'It truly depends on the role and it it makes sense to move my family'
 'My top preference is to work from home with a willingness to travel as needed.  I would consider relocating for a special opportunity.  ']
Current Employment Status: 127 unique values
Sample values: ['Freelancing' 'Working full time' 'Studying'
 'Volunteering,Working part time'
 'Freelancing,Volunteering,Studying,Unemployed / Seeking employment'
 'Unemployed / Seeking employment' 'Freelancing,Volunteering,Studying'
 'Working part time' 'Working full time,Volunteering'
 'Freelancing,Volunteering']
Money Managed: 297 unique values
Sample values: ['US$2000000' 'US$1000000' nan 'US$1200000' 'US$50' 'US$10000'
 'US$3000000' 'US$0' 'US$100000' 'US$700000']
Other Interests: 295 unique values
Sample values: ['Running a EA workplace or professional group,Advisor - Advising an effective organization'
 'Advisor - Advising an effective organization,Board Member - Sitting on the board of an effective organization'
 nan
 'Advisor - Advising an effective organization,Board Member - Sitting on the board of an effective organization,Pro-bono Work - Doing pro-bono work for an effective organization,Running a EA workplace or professional group'
 'Advisor - Advising an effective organization,Pro-bono Work - Doing pro-bono work for an effective organization,Running initiatives (like fundraising campaigns) at my organization'
 'Advisor - Advising an effective organization,Running a EA workplace or professional group'
 'Advisor - Advising an effective organization,Board Member - Sitting on the board of an effective organization,Running initiatives (like fundraising campaigns) at my organization'
 'Board Member - Sitting on the board of an effective organization'
 'Pro-bono Work - Doing pro-bono work for an effective organization'
 'Advisor - Advising an effective organization']
Profile Last Updated: 340 unique values
Sample values: ['2025-03-29' '2025-03-28' '2025-03-27' '2025-03-26' '2025-03-25'
 '2025-03-24' '2025-03-23' '2025-03-22' '2025-03-21' '2025-03-20']
Outdated Candidate: 2374 unique values
Sample values: ['https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recM7G6CghuNpl1Ae'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recqW9zfgwV96eN7y'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recYhm3g5zf7DlkVt'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=reciQqE8M7u4O1Jmu'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recSFNdgNlZUwKOmy'
 'https://airtable.com/shrSvHwSxxAOAPDxO?prefill_Candidate=recYDqVzsr070VYdI'

To examine discrepancies between datasets for the cause areas people are interested in, I am going to standardize the column names between them.

In [17]:
#syntactic and pattern based error detection/repair: standardizing cause areas. make column names upper or lowercase

# def cause_area_standardization(df, column_name):
#     df[column_name] = df[column_name].astype(str).str.strip()
#     df[column_name] = df[column_name].str.replace(r'\s*,\s*', ',', regex=True)
#     return df

In [18]:
# cause_area_standardization(CFI, "Cause Area Interests")
# CFI.head()

,Full Name,City,Country,Current Title,Current Employer,Large Firm Affiliation,LinkedIn,Career Path Interests,Cause Area Interests,Openness to a New Role
0,Abdullah Al Qayyim,New Brunswick,Canada,Independent consultant,"Abdullahandbeyond, MCAF",NaN,https://www.linkedin.com/in/abdullahandbeyond/,NaN,nan,NaN
1,Aditi Sharma,Bangalore,India,Consultant (2-4 years experience),VMware,NaN,https://www.linkedin.com/in/aditishm/,NaN,nan,NaN
2,Andrew Dornon,Austin,United States of America,Other,TaskHuman,NaN,https://www.linkedin.com/in/andrewdornon/,NaN,nan,NaN
3,Anurag Dey,Stockholm,Sweden,Consultant (2-4 years experience),Analysys Mason,NaN,https://www.linkedin.com/in/anuragdey/,NaN,nan,NaN
4,Barth Cabouat,Nairobi,Kenya,Other,One Acre Fund,NaN,https://www.linkedin.com/in/barthcabouat/,NaN,nan,NaN

In [8]:
#remove exact duplicates

In [9]:
# standardize key categorical values

In [10]:
# handle missing values

In [11]:
# convert data types and handle outliers

Merge point.

In [12]:
#result = pd.concat([CIF, HIP], axis=0, ignore_index=True)

In [13]:
# identify and handle post merge duplicates

In [14]:
# align and standardize final categorical fields if applicable

In [15]:
# final missing values check

In [16]:
# write new csv. end part 1 notebook.